[package]
name = "hyperon_capi"
version = "0.1.0"
authors = ["Vitaly Bogdanov <vsbogd@gmail.com>"]
edition = "2018"

[lib]
name = "hyperon_capi"
path = "src/lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
hyperon = { path = "../" }
