[build-system]
requires = ["setuptools>=46.1.0", "setuptools_scm[toml]>=5", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hyperson"
dependencies = [
    'importlib-metadata; python_version<"3.8"',
]
