# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'GitHub release tag (for example v0.1.2)'
        required: true
        type: string

jobs:

  build:

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-11]
      max-parallel: 3

    uses: ./.github/workflows/build.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
      make-packages: true
      publish: true
      release-tag: ${{ inputs.release-tag }}
