# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: 'Publish the python package to pypi'
        type: boolean
        required: true
        default: false
      test_site:
        description: 'Publish to pypi test site'
        type: boolean
        required: true
        default: false

permissions:
  contents: read

jobs:
  publish-pypi:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      max-parallel: 2

    steps:
    - uses: actions/checkout@v3

    - name: Download shared library artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist-${{ matrix.python-version }}.tar.gz
        path: python

    - name: Untar
      working-directory: ./python
      run: |
        tar zxf ${{ matrix.python-version }}.tar.gz

    - name: Publish package to pypi
      if: startsWith(github.ref, 'refs/tags') && ${{ inputs.publish_to_pypi }} && ${{ ! inputs.test_site }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: python/dist/

    - name: Publish package to test pypi
      if: startsWith(github.ref, 'refs/tags') && ${{ inputs.publish_to_pypi }} && ${{ inputs.test_site }} 
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        packages-dir: python/dist/

